name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'nx.json', 'workspace.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'nx.json', 'workspace.json') }}

      - name: Lint affected projects
        run: npx nx affected --target=lint --parallel=3 --base=main --head=HEAD

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'nx.json', 'workspace.json') }}

      - name: Run unit tests
        run: npx nx affected --target=test --parallel=3 --configuration=ci --base=main --head=HEAD

      - name: Run integration tests
        run: npx nx affected --target=integration-test --parallel=3 --base=main --head=HEAD

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report || true

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'nx.json', 'workspace.json') }}

      - name: Build affected projects
        run: npx nx affected --target=build --parallel=3 --base=main --head=HEAD --configuration=production || exit 1

      - name: Check if build succeeded
        id: check-build
        run: |
          if [ -d "dist/apps" ]; then
            echo "buildSucceeded=true" >> $GITHUB_ENV
          else
            echo "buildSucceeded=false" >> $GITHUB_ENV
          fi

      - name: List affected projects
        if: env.buildSucceeded == 'true'
        id: list-projects
        run: |
          echo "projectPaths=$(ls -d dist/apps/* 2>/dev/null)" >> $GITHUB_ENV

      - name: Archive and upload artifacts for each project
        if: env.buildSucceeded == 'true' && contains(github.event_name, 'push')
        run: |
          mkdir -p archived-artifacts
          for projectPath in ${{ env.projectPaths }}; do
            projectName=$(basename "$projectPath")
            echo "Archiving artifacts for project: $projectName"
            tar -czf "archived-artifacts/${projectName}.tar.gz" -C "$projectPath" .
          done

      - name: Upload all artifacts
        if: env.buildSucceeded == 'true' && contains(github.event_name, 'push')
        uses: actions/upload-artifact@v4
        with:
          name: all-project-artifacts
          path: archived-artifacts/

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'nx.json', 'workspace.json') }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-project-artifacts
          path: downloaded-artifacts

      - name: Debug downloaded artifacts
        run: |
          echo "Contents of downloaded-artifacts:"
          ls -R downloaded-artifacts || echo "No files found in downloaded-artifacts."

      - name: Check if artifacts exist
        id: check-artifacts
        run: |
          if ls downloaded-artifacts/*.tar.gz 1> /dev/null 2>&1; then
            echo "artifactsExist=true" >> $GITHUB_ENV
          else
            echo "artifactsExist=false" >> $GITHUB_ENV
          fi

      - name: Extract artifacts
        if: env.artifactsExist == 'true'
        run: |
          mkdir -p dist/apps
          for artifact in downloaded-artifacts/*.tar.gz; do
            projectName=$(basename "$artifact" .tar.gz)
            echo "Extracting artifact for project: $projectName"
            tar -xzf "$artifact" -C "dist/apps/$projectName"
          done

      - name: Run E2E tests for affected projects
        run: npx nx affected --target=e2e --parallel=3 --base=main --head=HEAD

      - name: Generate Allure E2E report
        run: npx allure generate cypress/allure-results --clean -o allure-e2e-report || true

      - name: Upload Allure E2E report
        uses: actions/upload-artifact@v4
        with:
          name: allure-e2e-report
          path: allure-e2e-report

  release:
    needs: [build, e2e]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'nx.json', 'workspace.json') }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-project-artifacts
          path: downloaded-artifacts

      - name: Debug downloaded artifacts
        run: |
          echo "Contents of downloaded-artifacts:"
          ls -R downloaded-artifacts || echo "No files found in downloaded-artifacts."

      - name: Check if artifacts exist
        id: check-artifacts
        run: |
          if ls downloaded-artifacts/*.tar.gz 1> /dev/null 2>&1; then
            echo "artifactsExist=true" >> $GITHUB_ENV
          else
            echo "artifactsExist=false" >> $GITHUB_ENV
          fi

      - name: Extract artifacts
        if: env.artifactsExist == 'true'
        run: |
          mkdir -p dist/apps
          for artifact in downloaded-artifacts/*.tar.gz; do
            projectName=$(basename "$artifact" .tar.gz)
            echo "Extracting artifact for project: $projectName"
            tar -xzf "$artifact" -C "dist/apps/$projectName"
          done

      - name: Release libraries
        run: npm run release-libs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-project-artifacts
          path: downloaded-artifacts

      - name: Debug downloaded artifacts
        run: |
          echo "Contents of downloaded-artifacts:"
          ls -R downloaded-artifacts || echo "No files found in downloaded-artifacts."

      - name: Check if artifacts exist
        id: check-artifacts
        run: |
          if ls downloaded-artifacts/*.tar.gz 1> /dev/null 2>&1; then
            echo "artifactsExist=true" >> $GITHUB_ENV
          else
            echo "artifactsExist=false" >> $GITHUB_ENV
          fi

      - name: Extract artifacts
        if: env.artifactsExist == 'true'
        run: |
          mkdir -p dist/apps
          for artifact in downloaded-artifacts/*.tar.gz; do
            projectName=$(basename "$artifact" .tar.gz)
            echo "Extracting artifact for project: $projectName"
            tar -xzf "$artifact" -C "dist/apps/$projectName"
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy all projects to AWS S3
        run: |
          for projectPath in dist/apps/*; do
            projectName=$(basename "$projectPath")
            echo "Deploying $projectName to S3..."
            aws s3 sync "$projectPath/" "s3://your-bucket-name/$projectName/"
          done

      - name: Verify deployment
        run: |
          for projectPath in dist/apps/*; do
            projectName=$(basename "$projectPath")
            echo "Verifying deployment for $projectName..."
            aws s3 ls "s3://your-bucket-name/$projectName/" --recursive
          done